### ISSUE TITLE
Exrules are missing from `to_hash`

### ISSUE THREAD

**Issue by ryanwilliams** [seejohnrun/ice_cube#395] opened 2017-05-10 05:08 UTC
We serialise a `Schedule` object to a hash using `Schedule#to_hash` so we can save it in our DB, but found that the `exrules` weren't being included in the hash which means when converted back they were lost. Digging into the code I see that they're only included when `IceCube.compatibility <= 11`, so we've just set that to 11 and it works fine apart from a deprecation warning here and there.

Is it supposed to behave this way? How are `exrules` meant to be handled in versions past 11?

**Comment by avit** [comment] 2017-05-10 14:42
Hi Ryan,

This was removed purposefully because it was all too easy to serialize a schedule that excludes itself, and this would cause apps to go into an infinite loop at some unexpected time in the future when the schedule gets reloaded.

Can you work around this by defining your schedules differently?

It might be possible for us to keep it in `to_hash` and only remove it when going `to_json` and `to_yaml` with a warning. That's open to discussion, so you could still shoot yourself in the foot with `to_hash.to_yaml`...

**Comment by avit** [comment] 2017-05-10 14:46
https://icalendar.org/iCalendar-RFC-5545/a-3-deprecated-features.html

**Comment by avit** [comment] 2017-07-10 06:28
Closing as duplicate of #127

**Closed by avit** 2017-07-10 06:28 UTC
Labels: question
