### ISSUE TITLE
from_ical not parsing with time zone

### ISSUE THREAD

**Issue by taareskjold** [seejohnrun/ice_cube#376] opened 2017-02-01 12:44 UTC
**DTSTART;TZID=Europe/Oslo:20170203T090000** gives schedule with **@start_time=2017-02-03 09:00:00 +0000**. It should be **@start_time=2017-02-03 09:00:00 +0100**.

Bug og something I'm doing wrong?

Event (from icloud.com-calendar)

`BEGIN:VEVENT\r\nCREATED:20170201T103147Z\r\nUID:01885971-AE07-44F1-9303-565D6ED68E53\r\nRRULE:FREQ=WEEKLY\r\nDTEND;TZID=Europe/Oslo:20170203T100000\r\nSUMMARY:Fridays at 9-10 in Oslo\r\nDTSTART;TZID=Europe/Oslo:20170203T090000\r\nDTSTAMP:20170201T122224Z\r\nSEQUENCE:0\r\nEND:VEVENT\r\n`

Parsing:

`IceCube::Schedule.from_ical(event)`

Result

`#<IceCube::Schedule:0x007fc3056c6798 @start_time=2017-02-03 09:00:00 +0000, @all_recurrence_rules=[#<IceCube::WeeklyRule:0x007fc2fef692d0 @validations={:interval=>[#<IceCube::Validations::WeeklyInterval::Validation:0x007fc2fef691e0 @interval=1, @week_start=:sunday>], :base_wday=>[#<IceCube::Validations::ScheduleLock::Validation:0x007fc2fef68f88 @type=:wday>], :base_hour=>[#<IceCube::Validations::ScheduleLock::Validation:0x007fc2fef68e98 @type=:hour>], :base_min=>[#<IceCube::Validations::ScheduleLock::Validation:0x007fc2fef68df8 @type=:min>], :base_sec=>[#<IceCube::Validations::ScheduleLock::Validation:0x007fc2fef68d30 @type=:sec>]}, @interval=1, @week_start=:sunday, @uses=0>], @all_exception_rules=[], @end_time=2017-02-03 10:00:00 +0000>`

**Comment by seejohnrun** [comment] 2017-02-01 13:41
hello and thanks for the report.  worth looking at https://github.com/seejohnrun/ice_cube/pull/335 (which addresses this) - and should have a fix for this soon!

**Comment by taareskjold** [comment] 2017-02-02 05:45
Thanks for your quick response! Looking forward to the fix. :-)

**Comment by avit** [comment] 2017-07-10 06:04
Closing as duplicate of #335

**Closed by avit** 2017-07-10 06:04 UTC
Labels: ical
